CR EQU 13
LF EQU 10

DATOS SEGMENT

       MENSAJE1 DB 'Tecnologico de Estudios Superiores de Jilotepec',CR,LF,'$'
       MENSAJE2 DB 'ING. SISTEMAS COMPUTACIONALES',CR,LF,'$'
       
       
DATOS ENDS

PILA SEGMENT STACK

    DB 64 DUP('PILA')
PILA ENDS

CODIGO SEGMENT

    LN PROC FAR
    
    ASSUME CS:CODIGO,DS:DATOS,SS:PILA
    MOV AX,DATOS
    MOV DS,AX
    LEA DX,MENSAJE1
    CALL ESCRIBE
    LEA DX,MENSAJE2
    CALL ESCRIBE
    MOV AX,4C00H
    INT 21H
    
    LN ENDP
    
    ESCRIBE PROC
    MOV AH,9
    INT 21H
    RET
    ESCRIBE ENDP
    
CODIGO ENDS

END LN